---
name: Question / Discussion
description: Ask a question or start a discussion
title: "[QUESTION] Brief description of your question"
labels: ["question", "discussion"]
assignees: []
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know or discuss?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information.

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: If applicable, describe what you've already tried or researched.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - **OS**: [e.g., Ubuntu 22.04, macOS 12.0, Windows 11]
        - **Python Version**: [e.g., 3.11.0]
        - **NextCraftTalk Version**: [e.g., 1.0.2]
        - **Deployment Mode**: [External AI / Self-hosted]

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might be helpful.

  - type: checkboxes
    id: resources
    attributes:
      label: Related Documentation
      description: Have you checked these resources?
      options:
        - label: README.md
        - label: GitHub Wiki
        - label: CHANGELOG.md
        - label: Existing Issues
        - label: Discord Community

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched existing issues and discussions
          required: true
        - label: This isn't covered in the documentation
          required: true
        - label: This is a genuine question (not a bug report or feature request)
          required: true
