---
name: Security Vulnerability
description: Report a security vulnerability (DO NOT use for general bugs)
title: "[SECURITY] Brief description of the vulnerability"
labels: ["security", "vulnerability"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 Security Vulnerability Report

        **⚠️ IMPORTANT**: This template is for reporting security vulnerabilities only. For general bugs, please use the Bug Report template instead.

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the security vulnerability. Be specific but avoid including exploit code.
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      options:
        - label: Data breach or exposure
        - label: Unauthorized access
        - label: Denial of service
        - label: Privilege escalation
        - label: Other (please specify in description)

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level (Your Assessment)
      options:
        - Critical - Immediate threat to data or systems
        - High - Significant security risk
        - Medium - Moderate security concern
        - Low - Minor security improvement needed
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the vulnerability. DO NOT include exploit code.
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept
      description: If you have a proof of concept, describe it without including actual exploit code.

  - type: input
    id: versions
    attributes:
      label: Affected Versions
      description: Which versions of NextCraftTalk are affected?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide environment details
      placeholder: |
        - **OS**: [e.g., Ubuntu 22.04]
        - **Python Version**: [e.g., 3.11.0]
        - **Deployment Mode**: [External AI / Self-hosted]
        - **Configuration**: Any specific configuration that enables this vulnerability

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this vulnerability, please describe them.

  - type: dropdown
    id: disclosure
    attributes:
      label: Disclosure Preferences
      options:
        - I would like to be credited for this finding
        - I prefer to remain anonymous
        - I would like to participate in the fix development

  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you for follow-up? (This will be kept confidential)

  - type: markdown
    attributes:
      value: |
        ---

        **Response Timeline**: We will acknowledge your report within 48 hours and provide updates throughout the process.
